### PR TITLE
Add Boulder

### PR DESCRIPTION
**Pull request by fiatflux**

### CODE REVIEW

**Comment by sellout** [comment]
I think @fiatflux and I probably have different perspectives on this – the entries here are mostly CU-centric, and I live on the opposite end of town, so instead of hearing how CU is ruining Boulder, I hear how we already have too many homeless shelters in North Boulder.

That is to say that I’m not familiar with most of these (other than lawns and Google), but they seem valid, just a different set of experiences. ¯\_(ツ)_/¯

**Comment by tedder** [comment]
Thanks. @fiatflux, it needs to be rebased/merge conflicts fixed anyhow, can you also make sure they are expected/recognizable to locals?

**Comment by fiatflux** [comment]
Rebased and removed some of the (slightly) more obscure ones. I'll let @sellout add the North Boulder bits.

**Comment by tedder** [comment]
Looks good.

**Pull request merged**
